// Edit charge codes and addresses here
// Format: { name: "Name", chargeCodeSZ: "SZ02B04D33", chargeCodeMOS: "MOS12345", address: "123 Main St, City, MO 64101" }
const CATEGORIES = {
    "Tower Sites": [
        { name: "Bennington RF Sub-Site", chargeCodeSZ: "SZ02B040107", chargeCodeMOS: "", address: "11231 Bennington Ave, Kansas City, MO 64134" },
        { name: "Booth RF Sub-Site", chargeCodeSZ: "SZ02B040105", chargeCodeMOS: "", address: "6801 Booth St, Kansas City, MO 64133" },
        { name: "City Hall RF Sub-Site", chargeCodeSZ: "SZ02B040102", chargeCodeMOS: "", address: "414 E 12 St, Kansas City, MO 64106" },
        { name: "Clay County RF Sub-Site", chargeCodeSZ: "SZ02B040110", chargeCodeMOS: "", address: "16616 NE 116 St, Kansas City, MO 64060" },
        { name: "KCI RF Sub-Site", chargeCodeSZ: "SZ02B040103", chargeCodeMOS: "", address: "9205 NW 112 St, Kansas City, MO 64153" },
        { name: "North Patrol Master Site", chargeCodeSZ: "SZ02B04", chargeCodeMOS: "", address: "1001 NW Barry Rd, Kansas City, MO 64154" },
        { name: "North Patrol Prime Site", chargeCodeSZ: "SZ02B0401", chargeCodeMOS: "", address: "1001 NW Barry Rd, Kansas City, MO 64154" },
        { name: "North Patrol RF Sub-Site", chargeCodeSZ: "SZ02B040101", chargeCodeMOS: "", address: "1001 NW Barry Rd, Kansas City, MO 64154" },
        { name: "Riverside RF Sub-Site", chargeCodeSZ: "SZ02B040109", chargeCodeMOS: "", address: "4191-4399 NW Tillison Rd, Kansas City, MO 64150" },
        { name: "Tower Park RF Sub-Site", chargeCodeSZ: "SZ02B040106", chargeCodeMOS: "", address: "7500 Holmes Rd, Kansas City, MO 64131" },
        { name: "UMKC RF Sub-Site", chargeCodeSZ: "SZ02B040108", chargeCodeMOS: "", address: "988 E 52 St, Kansas City, MO 64110" },
        { name: "Van Brunt RF Sub-Site", chargeCodeSZ: "SZ02B040111", chargeCodeMOS: "", address: "5301 E 27 St, Kansas City, MO 64127" },
        { name: "WOF RF Sub-Site", chargeCodeSZ: "SZ02B040104", chargeCodeMOS: "", address: "4923 N Winchester Ave, Kansas City, MO 64119" },
    ],
    "Independence Prime": [
        { name: "40 Highway RF Sub-Site", chargeCodeSZ: "SZ02B040205", chargeCodeMOS: "", address: "" },
        { name: "Adams Dairy RF Sub-Site", chargeCodeSZ: "SZ02B040207", chargeCodeMOS: "", address: "" },
        { name: "Commanders Hill RF Sub-Site", chargeCodeSZ: "SZ02B040204", chargeCodeMOS: "", address: "" },
        { name: "Independence Prime Site", chargeCodeSZ: "SZ02B0402", chargeCodeMOS: "", address: "" },
        { name: "LaFarge RF Sub-Site", chargeCodeSZ: "SZ02B040206", chargeCodeMOS: "", address: "" },
        { name: "Mason School RF Sub-Site", chargeCodeSZ: "SZ02B040208", chargeCodeMOS: "", address: "" },
        { name: "Massman RF Sub-Site", chargeCodeSZ: "SZ02B040201", chargeCodeMOS: "", address: "" },
        { name: "Water Department RF Sub-Site", chargeCodeSZ: "SZ02B040203", chargeCodeMOS: "", address: "" },
        { name: "Woods Chapel RF Sub-Site", chargeCodeSZ: "SZ02B040202", chargeCodeMOS: "", address: "" },
    ],
    "Platte County": [
        { name: "Leavenworth RF Sub-Site", chargeCodeSZ: "SZ02B040304", chargeCodeMOS: "", address: "" },
        { name: "Lewis School RF Sub-Site", chargeCodeSZ: "SZ02B040305", chargeCodeMOS: "", address: "" },
        { name: "North Tower RF Sub-Site", chargeCodeSZ: "SZ02B040301", chargeCodeMOS: "", address: "" },
        { name: "South Tower RF Sub-Site", chargeCodeSZ: "SZ02B040303", chargeCodeMOS: "", address: "" },
        { name: "Trimble RF Sub-Site", chargeCodeSZ: "SZ02B040302", chargeCodeMOS: "", address: "" },
    ],
    "Cass County": [
        { name: "Freeman RF Sub-Site", chargeCodeSZ: "SZ02B040406", chargeCodeMOS: "", address: "" },
        { name: "Garden City RF Sub-Site", chargeCodeSZ: "SZ02B040405", chargeCodeMOS: "", address: "" },
        { name: "KC Web RF Sub-Site", chargeCodeSZ: "SZ02B040404", chargeCodeMOS: "", address: "" },
        { name: "Pleasant Hill RF Sub-Site", chargeCodeSZ: "SZ02B040403", chargeCodeMOS: "", address: "" },
        { name: "Quarry RF Sub-Site", chargeCodeSZ: "SZ02B040402", chargeCodeMOS: "", address: "" },
    ],
    "Jackson County": [
        { name: "(Jackson County) Lone Jack ISR", chargeCodeSZ: "SZ02B0405", chargeCodeMOS: "", address: "" },
        { name: "(Jackson County) Oak Grove ISR", chargeCodeSZ: "SZ02B0406", chargeCodeMOS: "", address: "" },
    ],
    "Miscellaneous": [
        { name: "AIS Logging Dispatch Co-Located with Master Site", chargeCodeSZ: "SZ02B04D105", chargeCodeMOS: "", address: "" },
        { name: "Tower Park (CCGW Only)", chargeCodeSZ: "SZ02B04D14", chargeCodeMOS: "", address: "" },
        { name: "Training", chargeCodeSZ: "", chargeCodeMOS: "", address: "" },
    ],
    "Lees Summit": [
        { name: "Every RF Sub-Site", chargeCodeSZ: "SZ02B040702", chargeCodeMOS: "", address: "" },
        { name: "Ranson RF Sub-Site", chargeCodeSZ: "SZ02B040703", chargeCodeMOS: "", address: "" },
        { name: "Scherer RF Sub-Site", chargeCodeSZ: "SZ02B040701", chargeCodeMOS: "", address: "" },
        { name: "Woods RF Sub-Site", chargeCodeSZ: "SZ02B040704", chargeCodeMOS: "", address: "" },
    ],
    "(Johnson County MO) JCCD": [
        { name: "Centerview RF Sub-Site", chargeCodeSZ: "SZ02B040905", chargeCodeMOS: "", address: "" },
        { name: "Concord RF Sub-Site", chargeCodeSZ: "SZ02B040903", chargeCodeMOS: "", address: "" },
        { name: "Holden RF Sub-Site", chargeCodeSZ: "SZ02B040907", chargeCodeMOS: "", address: "" },
        { name: "Leeton RF Sub-Site", chargeCodeSZ: "SZ02B040904", chargeCodeMOS: "", address: "" },
        { name: "Rosehill RF Sub-Site", chargeCodeSZ: "SZ02B040906", chargeCodeMOS: "", address: "" },
        { name: "Warrensburg RF Sub-Site", chargeCodeSZ: "SZ02B040902", chargeCodeMOS: "", address: "" },
    ],
    "Police": [
        { name: "(Johnson County MO) JCCD", chargeCodeSZ: "SZ02B0409", chargeCodeMOS: "", address: "" },
        { name: "Belton Dispatch", chargeCodeSZ: "SZ02B04D23", chargeCodeMOS: "", address: "" },
        { name: "Belton PD RF Sub-Site", chargeCodeSZ: "SZ02B040401", chargeCodeMOS: "", address: "" },
        { name: "Blue Springs Dispatch", chargeCodeSZ: "SZ02B04D17", chargeCodeMOS: "", address: "" },
        { name: "Cass County", chargeCodeSZ: "SZ02B0404", chargeCodeMOS: "", address: "" },
        { name: "Cass County Sherrif Dispatch", chargeCodeSZ: "SZ02B04D22", chargeCodeMOS: "", address: "" },
        { name: "Clay County Dispatch", chargeCodeSZ: "SZ02B04D8", chargeCodeMOS: "", address: "" },
        { name: "Clay County NM Client", chargeCodeSZ: "SZ02B04D27", chargeCodeMOS: "", address: "" },
        { name: "EOC Dispatch", chargeCodeSZ: "SZ02B04D33", chargeCodeMOS: "", address: "" },
        { name: "Excelsior Springs", chargeCodeSZ: "SZ02B04D32", chargeCodeMOS: "", address: "" },
        { name: "Excelsior Springs", chargeCodeSZ: "SZ02B0408", chargeCodeMOS: "", address: "" },
        { name: "Gladstone Dispatch", chargeCodeSZ: "SZ02B04D8", chargeCodeMOS: "", address: "" },
        { name: "Grandview Dispatch", chargeCodeSZ: "SZ02B04D26", chargeCodeMOS: "", address: "" },
        { name: "Harissonville Dispatch", chargeCodeSZ: "SZ02B04D24", chargeCodeMOS: "", address: "" },
        { name: "Independence Dispatch", chargeCodeSZ: "SZ02B04D16", chargeCodeMOS: "", address: "" },
        { name: "Independence Dispatch", chargeCodeSZ: "SZ02B04D31", chargeCodeMOS: "", address: "" },
        { name: "JCCD Dispatch", chargeCodeSZ: "SZ02B04D14", chargeCodeMOS: "", address: "" },
        { name: "Jackson County Dispatch", chargeCodeSZ: "SZ02B04D3", chargeCodeMOS: "", address: "" },
        { name: "Jackson County Jail", chargeCodeSZ: "SZ02B04D7", chargeCodeMOS: "", address: "" },
        { name: "KCI Dispatch", chargeCodeSZ: "SZ02B04D5", chargeCodeMOS: "", address: "" },
        { name: "KCMO Radio Shop Dispatch", chargeCodeSZ: "SZ02B04D15", chargeCodeMOS: "", address: "" },
        { name: "KCPD 1111 Locust Dispatch", chargeCodeSZ: "SZ02B04D1", chargeCodeMOS: "", address: "" },
        { name: "KCPD South Patrol Dispatch", chargeCodeSZ: "SZ02B04D4", chargeCodeMOS: "", address: "" },
        { name: "KCPD South Patrol Dispatch (Was Agnes)", chargeCodeSZ: "SZ02B04D4", chargeCodeMOS: "", address: "" },
        { name: "LERC Dispatch", chargeCodeSZ: "SZ02B04D34", chargeCodeMOS: "", address: "" },
        { name: "Lees Summit", chargeCodeSZ: "SZ02B0407", chargeCodeMOS: "", address: "" },
        { name: "Lees Summit PD Dispatch", chargeCodeSZ: "SZ02B04D29", chargeCodeMOS: "", address: "" },
        { name: "Liberty Dispatch", chargeCodeSZ: "SZ02B04D8", chargeCodeMOS: "", address: "" },
        { name: "Liberty Dispatch (NM Client)", chargeCodeSZ: "SZ02B04D13", chargeCodeMOS: "", address: "" },
        { name: "North KC Dispatch", chargeCodeSZ: "SZ02B04D9", chargeCodeMOS: "", address: "" },
        { name: "North Patrol Tech (CCGW) Only", chargeCodeSZ: "SZ02B04D11", chargeCodeMOS: "", address: "" },
        { name: "Platte County", chargeCodeSZ: "SZ02B0403", chargeCodeMOS: "", address: "" },
        { name: "Platte County BU Dispatch", chargeCodeSZ: "SZ02B04D19", chargeCodeMOS: "", address: "" },
        { name: "Platte County Dispatch", chargeCodeSZ: "SZ02B04D18", chargeCodeMOS: "", address: "" },
        { name: "Pleasant Hill Dispatch", chargeCodeSZ: "SZ02B04D25", chargeCodeMOS: "", address: "" },
        { name: "Pleasant Valley Dispatch", chargeCodeSZ: "SZ02B04D28", chargeCodeMOS: "", address: "" },
        { name: "Raymore Dispatch", chargeCodeSZ: "SZ02B04D21", chargeCodeMOS: "", address: "" },
        { name: "Raytown Dispatch", chargeCodeSZ: "SZ02B04D12", chargeCodeMOS: "", address: "" },
        { name: "Riverside Dispatch", chargeCodeSZ: "SZ02B04D6", chargeCodeMOS: "", address: "" },
        { name: "UMKC Police Dispatch", chargeCodeSZ: "SZ02B04D20", chargeCodeMOS: "", address: "" },
        { name: "VA Hospital Dispatch", chargeCodeSZ: "SZ02B04D10", chargeCodeMOS: "", address: "" },
        { name: "WOF (CCGW Only)", chargeCodeSZ: "SZ02B04D13", chargeCodeMOS: "", address: "" },
        { name: "Water Dispatch", chargeCodeSZ: "SZ02B04D7", chargeCodeMOS: "", address: "" },
    ],
    "Fire": [
        { name: "KCFD Backup 1111 Locust Dispatch", chargeCodeSZ: "SZ02B04D3", chargeCodeMOS: "", address: "" },
        { name: "KCFD Eastwood Dispatch", chargeCodeSZ: "SZ02B04D2", chargeCodeMOS: "", address: "" },
        { name: "Lees Summit FD Dispatch", chargeCodeSZ: "SZ02B04D30", chargeCodeMOS: "", address: "" },
    ],
};
