// Edit charge codes and addresses here
// Format: { name: "Name", chargeCode: "SZ02B04D33", address: "123 Main St, City, MO 64101" }
const CATEGORIES = {
    "Tower Sites": [
        { name: "(Jackson County) Lone Jack ISR", chargeCode: "SZ02B0405", address: "Add address here" },
        { name: "(Jackson County) Oak Grove ISR", chargeCode: "SZ02B0406", address: "Add address here" },
        { name: "40 Highway RF Sub-Site", chargeCode: "SZ02B040205", address: "Add address here" },
        { name: "AIS Logging Dispatch Co-Located with Master Site", chargeCode: "SZ02B04D105", address: "Add address here" },
        { name: "Adams Dairy RF Sub-Site", chargeCode: "SZ02B040207", address: "Add address here" },
        { name: "Bennington RF Sub-Site", chargeCode: "SZ02B040107", address: "Add address here" },
        { name: "Booth RF Sub-Site", chargeCode: "SZ02B040105", address: "Add address here" },
        { name: "Centerview RF Sub-Site", chargeCode: "SZ02B040905", address: "Add address here" },
        { name: "City Hall RF Sub-Site", chargeCode: "SZ02B040102", address: "Add address here" },
        { name: "Clay County RF Sub-Site", chargeCode: "SZ02B040110", address: "Add address here" },
        { name: "Commanders Hill RF Sub-Site", chargeCode: "SZ02B040204", address: "Add address here" },
        { name: "Concord RF Sub-Site", chargeCode: "SZ02B040903", address: "Add address here" },
        { name: "Every RF Sub-Site", chargeCode: "SZ02B040702", address: "Add address here" },
        { name: "Freeman RF Sub-Site", chargeCode: "SZ02B040406", address: "Add address here" },
        { name: "Garden City RF Sub-Site", chargeCode: "SZ02B040405", address: "Add address here" },
        { name: "Holden RF Sub-Site", chargeCode: "SZ02B040907", address: "Add address here" },
        { name: "Independence Prime Site", chargeCode: "SZ02B0402", address: "Add address here" },
        { name: "KC Web RF Sub-Site", chargeCode: "SZ02B040404", address: "Add address here" },
        { name: "KCI RF Sub-Site", chargeCode: "SZ02B040103", address: "Add address here" },
        { name: "LaFarge RF Sub-Site", chargeCode: "SZ02B040206", address: "Add address here" },
        { name: "Leavenworth RF Sub-Site", chargeCode: "SZ02B040304", address: "Add address here" },
        { name: "Leeton RF Sub-Site", chargeCode: "SZ02B040904", address: "Add address here" },
        { name: "Lewis School RF Sub-Site", chargeCode: "SZ02B040305", address: "Add address here" },
        { name: "Mason School RF Sub-Site", chargeCode: "SZ02B040208", address: "Add address here" },
        { name: "Massman RF Sub-Site", chargeCode: "SZ02B040201", address: "Add address here" },
        { name: "North Tower RF Sub-Site", chargeCode: "SZ02B040301", address: "Add address here" },
        { name: "Pleasant Hill RF Sub-Site", chargeCode: "SZ02B040403", address: "Add address here" },
        { name: "Quarry RF Sub-Site", chargeCode: "SZ02B040402", address: "Add address here" },
        { name: "Ranson RF Sub-Site", chargeCode: "SZ02B040703", address: "Add address here" },
        { name: "Riverside RF Sub-Site", chargeCode: "SZ02B040109", address: "Add address here" },
        { name: "Rosehill RF Sub-Site", chargeCode: "SZ02B040906", address: "Add address here" },
        { name: "Scherer RF Sub-Site", chargeCode: "SZ02B040701", address: "Add address here" },
        { name: "South Tower RF Sub-Site", chargeCode: "SZ02B040303", address: "Add address here" },
        { name: "Tower Park (CCGW Only)", chargeCode: "SZ02B04D14", address: "Add address here" },
        { name: "Tower Park RF Sub-Site", chargeCode: "SZ02B040106", address: "Add address here" },
        { name: "Trimble RF Sub-Site", chargeCode: "SZ02B040302", address: "Add address here" },
        { name: "UMKC RF Sub-Site", chargeCode: "SZ02B040108", address: "Add address here" },
        { name: "Van Brunt RF Sub-Site", chargeCode: "SZ02B040111", address: "Add address here" },
        { name: "WOF RF Sub-Site", chargeCode: "SZ02B040104", address: "Add address here" },
        { name: "Warrensburg RF Sub-Site", chargeCode: "SZ02B040902", address: "Add address here" },
        { name: "Water Department RF Sub-Site", chargeCode: "SZ02B040203", address: "Add address here" },
        { name: "Woods Chapel RF Sub-Site", chargeCode: "SZ02B040202", address: "Add address here" },
        { name: "Woods RF Sub-Site", chargeCode: "SZ02B040704", address: "Add address here" },
    ],
    "Police Stations": [
        { name: "Belton PD RF Sub-Site", chargeCode: "SZ02B040401", address: "Add address here" },
        { name: "Jackson County Jail", chargeCode: "SZ02B04D7", address: "Add address here" },
        { name: "KCPD 1111 Locust Dispatch", chargeCode: "SZ02B04D1", address: "Add address here" },
        { name: "KCPD South Patrol Dispatch", chargeCode: "SZ02B04D4", address: "Add address here" },
        { name: "KCPD South Patrol Dispatch (Was Agnes)", chargeCode: "SZ02B04D4", address: "Add address here" },
        { name: "Lees Summit PD Dispatch", chargeCode: "SZ02B04D29", address: "Add address here" },
        { name: "North Patrol Master Site", chargeCode: "SZ02B04", address: "Add address here" },
        { name: "North Patrol Prime Site", chargeCode: "SZ02B0401", address: "Add address here" },
        { name: "North Patrol RF Sub-Site", chargeCode: "SZ02B040101", address: "Add address here" },
        { name: "North Patrol Tech (CCGW Only)", chargeCode: "SZ02B04D11", address: "Add address here" },
        { name: "North Patrol Tech (CCGW) Only", chargeCode: "SZ02B04D11", address: "Add address here" },
        { name: "UMKC Police Dispatch", chargeCode: "SZ02B04D20", address: "Add address here" },
    ],
    "Fire Stations": [
        { name: "KCFD Backup 1111 Locust Dispatch", chargeCode: "SZ02B04D3", address: "Add address here" },
        { name: "KCFD Eastwood Dispatch", chargeCode: "SZ02B04D2", address: "Add address here" },
        { name: "Lees Summit FD Dispatch", chargeCode: "SZ02B04D30", address: "Add address here" },
    ],
    "General Dispatch": [
        { name: "(Johnson County MO) JCCD", chargeCode: "SZ02B0409", address: "Add address here" },
        { name: "Belton Dispatch", chargeCode: "SZ02B04D23", address: "Add address here" },
        { name: "Blue Springs Dispatch", chargeCode: "SZ02B04D17", address: "Add address here" },
        { name: "Cass County", chargeCode: "SZ02B0404", address: "Add address here" },
        { name: "Cass County Sherrif Dispatch", chargeCode: "SZ02B04D22", address: "Add address here" },
        { name: "Clay County Dispatch", chargeCode: "SZ02B04D8", address: "Add address here" },
        { name: "Clay County NM Client", chargeCode: "SZ02B04D27", address: "Add address here" },
        { name: "EOC Dispatch", chargeCode: "SZ02B04D33", address: "Add address here" },
        { name: "Excelsior Springs", chargeCode: "SZ02B04D32", address: "Add address here" },
        { name: "Excelsior Springs", chargeCode: "SZ02B0408", address: "Add address here" },
        { name: "Gladstone Dispatch", chargeCode: "SZ02B04D8", address: "Add address here" },
        { name: "Grandview Dispatch", chargeCode: "SZ02B04D26", address: "Add address here" },
        { name: "Harissonville Dispatch", chargeCode: "SZ02B04D24", address: "Add address here" },
        { name: "Independence Dispatch", chargeCode: "SZ02B04D16", address: "Add address here" },
        { name: "Independence Dispatch", chargeCode: "SZ02B04D31", address: "Add address here" },
        { name: "JCCD Dispatch", chargeCode: "SZ02B04D14", address: "Add address here" },
        { name: "Jackson County Dispatch", chargeCode: "SZ02B04D3", address: "Add address here" },
        { name: "KCI Dispatch", chargeCode: "SZ02B04D5", address: "Add address here" },
        { name: "KCMO Radio Shop Dispatch", chargeCode: "SZ02B04D15", address: "Add address here" },
        { name: "LERC Dispatch", chargeCode: "SZ02B04D34", address: "Add address here" },
        { name: "Lees Summit", chargeCode: "SZ02B0407", address: "Add address here" },
        { name: "Liberty Dispatch", chargeCode: "SZ02B04D8", address: "Add address here" },
        { name: "Liberty Dispatch (NM Client)", chargeCode: "SZ02B04D13", address: "Add address here" },
        { name: "North KC Dispatch", chargeCode: "SZ02B04D9", address: "Add address here" },
        { name: "Platte County", chargeCode: "SZ02B0403", address: "Add address here" },
        { name: "Platte County BU Dispatch", chargeCode: "SZ02B04D19", address: "Add address here" },
        { name: "Platte County Dispatch", chargeCode: "SZ02B04D18", address: "Add address here" },
        { name: "Pleasant Hill Dispatch", chargeCode: "SZ02B04D25", address: "Add address here" },
        { name: "Pleasant Valley Dispatch", chargeCode: "SZ02B04D28", address: "Add address here" },
        { name: "Raymore Dispatch", chargeCode: "SZ02B04D21", address: "Add address here" },
        { name: "Raytown Dispatch", chargeCode: "SZ02B04D12", address: "Add address here" },
        { name: "Riverside Dispatch", chargeCode: "SZ02B04D6", address: "Add address here" },
        { name: "VA Hospital Dispatch", chargeCode: "SZ02B04D10", address: "Add address here" },
        { name: "WOF (CCGW Only)", chargeCode: "SZ02B04D13", address: "Add address here" },
        { name: "Water Dispatch", chargeCode: "SZ02B04D7", address: "Add address here" },
    ]
};
